# CONFIG
# Twitter API keys
CONSUMER_KEY =  "YOUR CONSUMER KEY"
CONSUMER_SECRET =  "YOUR CONSUMER SECRET"
ACCESS_TOKEN =  "YOUR ACESS TOKEN"
ACCESS_TOKEN_SECRET = "YOUR ACCESS TOKEN SECRET"

# Twitter API parameters
TEST = True
TWITTER_PRODUCT = "fullarchive"
TWITTER_ENVIRONMENT = "dev"

# SQLAlchemy database connection parameters
DB_ADDRESS = "DB ADDRESS:PORT"
DB_USERNAME = "DB USERNAME"
DB_PASSWORD = "DB PASSWORD"
DB_NAME = "NAME OF DATABASE"

# Show log output to console
STDOUT = False
